### ISSUE TITLE
Pathways count mismatch

### ISSUE THREAD

**Issue by stain** [openphacts/ops-platform-setup#2]
http://heater.cs.man.ac.uk:3002/pathways/count gives 1437 - while the production 1.5 at https://beta.openphacts.org/1.5/pathways/count?app_id=161aeb7d&app_key=bbcba81896020f0b95e3dd35b55e3345  and dev  http://ops2.few.vu.nl/1.5/pathways/count  both says 1448. Why?

**Comment by egonw** [comment]
Ian, Ryan, I am not sure if this is not outdated by the loading of the new data, but an issue to keep being aware of...

**Comment by stain** [comment]
I will check further if this is caused by a mismatch in the data loaded on ops2 before 1.5 release, and the data loaded from http://data.openphacts.org/1.5/rdf/ as used in the Docker image.

**Comment by stain** [comment]
Docker image now uses the 1.5 virtuoso dump instead of a fresh rdf load.

I now get 1448 at heater as well. - still not quite explained, so agree with @egonw to just stay aware of this.
